### ISSUE TITLE
Proxies getting 407

### ISSUE THREAD

**Issue by johnmarkacala** [DKanarsky/scrapy-dynamic-sessions#1]
Im getting 407 error in my proxies though I've tested the proxies through cmd curl so I assumed it's not the problem
`curl --proxy <PROXY>:<PORT> --proxy-user <USER>:<PASS> "http://lumtest.com/myip.json"`

My format is also the same with the the read.me and are line separated.
`http://<USER>:<PASS>@<PROXY>:<PORT>`

I also tried only using one proxy inside the txt file but still the same

Please help. I can email you the proxy to test it out

**Comment by DKanarsky** [comment]
I have just tested with my own proxy with auth and it works fine. Did you try any other (publicly available, for example) proxies with authentication?
